### ISSUE TITLE
...

### ISSUE THREAD

**Issue by fat-lobyte** [KSP-RO/SovietSpacecraft#10]
...

**Comment by raidernick** [comment]
There is nothing wrong with the legs fitting in the fairings. I modeled the fairing when I made it around the lk model to make sure it fit. I've used it countless times in game and it works fine so I have no idea what you are talking about.

Here is a picture of the l3 stack and the lk is inside there and no legs are sticking out. I think I would've noticed something this obvious when making the parts you are clearly doing something wrong.

https://i.imgur.com/63pySzu.png

**Comment by fat-lobyte** [comment]
Did you not look at the drawings and pictures? Please just browse through them. It's pretty clear that the retracted legs are too far apart.

What is the diameter of your fairing and of your Blok G? You can just compare it to the marked diameters in the diagrams.

**Comment by raidernick** [comment]
I could but I have a lot more important things to be working on than a slight clipping problem between one of my parts and someone else's mod. I have hundreds of things on my backlog and seeing as how this isn't an ACTUAL issue with my part pack by itself, only if you try to use it with something else, it doesn't even make my list of things to care about sorry.

**Comment by fat-lobyte** [comment]
> how this isn't an ACTUAL issue with my part pack by itself

The diameter is **wrong**. I pointed to the documentation backing it up and what the correct diameter and shape is. I could go digging for some more, but I have a feeling that this would be a waste of time.  

Whether or not this constitutes an "ACTUAL issue" is for you to decide, but let's just say there would be no problems at all interfacing with "someone elses mod" if the diameter weren't **wrong**.

Especially if the "someone elses mod" is ProceduralFairings that I used solely to demonstrate the size.

If you don't have time, you don't have time, I understand that very well. I'll let it go and try to find another LK-Lander model. But please don't pretend it's a problem with "someone elses mod" when it's the part from *your* mod that is incorrectly modeled.

**Comment by fat-lobyte** [comment]
http://www.russianspaceweb.com/lk.html

> In its launch configuration, the stowed landing gear would have a span of 2.26 meters. (231)

Doesn't get much clearer than this.
