### ISSUE TITLE
Vostok/Voskhod Reentry 

### ISSUE THREAD

**Issue by wm1248** [KSP-RO/SovietSpacecraft#4]
The Vostok/Voskhod capsules fail to slow upon reentry with stock aero on KSP 1.3.

**Comment by raidernick** [comment]
wrong, i just tested it with no other mods installed in a clean ksp 1.3 and it slows down just fine. You have another broken mod somewhere causing the issue.

**Comment by zenmetsu** [comment]
I can also confirm that it works just fine in 1.3
