### ISSUE TITLE
Enhancement request - Vernier Orientation Indicators

### ISSUE THREAD

**Issue by zenmetsu** [KSP-RO/SovietSpacecraft#5]
Hey,
First of all, I really love your work, just one minor nitpick.  The vernier engines will only tilt in one axis, and it is possible to attach them in such a way that you have two pairs working together in yaw or pitch, thus losing authority in the missing axis.  The Block I verniers are an excellent example.  The R7 core/booster verniers have thin pipes which make alignment easy, but there is no way to know how the Block I verniers are aligned, you have to test it out in flight or on the pad to verify.  Maybe a small hint with the textures would be worthwhile to avoid frustration.

Thanks!
Jason

**Comment by raidernick** [comment]
a marking would be unrealistic, if you want to know the alignment the textures on them have a seam if you look closely makes them easy to align.

**Comment by zenmetsu** [comment]
I the seam is there, thanks for the pointer.  I'll go ahead and close this.  I might tweak the texture a bit so an indicator is visible on the part of the vernier that is inside the rocket and hidden once attached since the seam is a pain to see unless the lighting is really good.
