### ISSUE TITLE
Soyuz's Launch Escape System - wrong position

### ISSUE THREAD

**Issue by DeadlyMercury** [KSP-RO/SovietSpacecraft#6]
I see a problem with Soyuz's LES - it is placed good in save files, but it places wrong if you try to move it / deattach and attach again it.
Problem caused due to different instrument module heights (7K-OK + toroidal tank is higher than 7K-T or T) and different docking ports (ASAP looks really bad...)
I think that LES tower should mount on fairing, not on docking port or somewhere on ship...

Proof:
https://www.youtube.com/watch?v=HOrIEKAKVT0

I will be very happy if you fix this bug :)

**Comment by raidernick** [comment]
it's not a bug. the les can't be mounted on a fairing because of how ksp works. Either you need to add 100 different node positions to the parts or you can just tweak them like everyone else does, not a bug, closed

**Comment by DeadlyMercury** [comment]
Maybe it's better to make fairing and LES looks like Zond/7K-L1?
Also can you give a link about tweaking part node?
