### ISSUE TITLE
Can't download any of the files

### ISSUE THREAD

**Issue by Rex1812** [KSP-RO/SovietSpacecraft#7]
Hi I can no longer download any of the KSP-RO/SovietSpacecraft  files- your stations mods downloaded just fine.

J.

**Comment by DeadlyMercury** [comment]
I don't think it is mod issue.. It just can't be mod issue! - it could be your connection or browser issue.
Try to use git client or different browser. I just downloaded zip-file via browser (SovietSpacecraft-master.zip, ~85mb) and via git client:

~/git$ git clone https://github.com/KSP-RO/SovietSpacecraft.git
Cloning into 'SovietSpacecraft'...
remote: Counting objects: 876, done.
remote: Total 876 (delta 0), reused 0 (delta 0), pack-reused 876
Receiving objects: 100% (876/876), 95.77 MiB | 1.66 MiB/s, done.
Resolving deltas: 100% (433/433), done.
Checking connectivity... done.
