### ISSUE TITLE
Add support for KSP 1.4.1

### ISSUE THREAD

**Issue by TTFH** [KSP-RO/SovietSpacecraft#8]
In KSP 1.4.1 with the Making History Expansion, Kerbals have a pink halmet and there is a log spam with:

`Material doesn't have a texture property '_BumpMap'`
`MissingFieldException: Field '.KSPParticleEmitter.pe' not found.`

**Comment by raidernick** [comment]
This doesn't modify kerbals in any way so that is unrelated to this mod. Also, I made it explicitly clear I'm not supporting anything past 1.3.1 anymore so even if it was this mod, I'm not fixing it.
